### ISSUE TITLE
Python package errors

### ISSUE THREAD

**Issue by robertgreenhalgh** [chenlab-sj/Seq2Karyotype#1]
Errors are encountered with pandas and shiny if the latest versions are installed (see attached). Older versions of both packages are fine. Suggest changing the virtual environment setup command to the following:

conda -create -n s2k python=3.11 pandas=1.5.2 shiny==0.6.0

[Pandas.Error.txt](https://github.com/user-attachments/files/17511538/Pandas.Error.txt)
[Shiny.Error.txt](https://github.com/user-attachments/files/17511539/Shiny.Error.txt)

**Comment by pulimeng** [comment]
Thank you!
